### ISSUE TITLE
HOME

### ISSUE THREAD

**Issue by guaard** [ajoron/fit-and-run#10]
ORDINATEUR :

1 - Réduire les bulles Running et Training car elles me paraissent très grande.
2 - Revoir les ombres porté car elles sont trop compressé (ref: voir sur le .Psd)
3 - Il y a deux fois 'Fit & Run' sur la page, c'est normal ?

SMARTPHONE :

1 - Réduire les bulles Running et Training car elles me paraissent très grande.
2 - Supprimer les ombres portés car en responsive elle sont les une sur les autres.

**Comment by ajoron** [comment]
Voir pour les tailles des bulles

**Comment by ajoron** [comment]
OK
