### ISSUE TITLE
TRAINING

### ISSUE THREAD

**Issue by guaard** [ajoron/fit-and-run#11]
ORDINATEUR :

Menu:
1 - Logo Fit & Run plus gros que sur mes maquettes et pas très bien centré dans la barre blanche. Il y a plus d'espace en haut que en bas.
2 - Training et Running pixelisés
3 - Il manque Twitter et Facebook non ? (voir .Psd)

Page :
1 - Les textes me paraissent plus gros que sur les maquettes et pas de la même couleur (voir .Psd)
2 - Le pictogramme du calendrier est différent (voir .Psd)
3 - Connexion à mon compte est en gris et plus petit (voir .Psd)
4 - Le fond n'est pas le bon (voir .Psd)

SMARTPHONE :

Menu 
1 - Le logo n'a pas de marge à gauche (mettre 10pixel ou plus à voir)
(https://cloud.githubusercontent.com/assets/12978755/8267667/fe81de26-1740-11e5-9863-aac1d47d3f3c.png)
2 - le pico du menu n'est pas centré dans la barre blanche, il est collé en haut à droite.

Page :
1 - Les bulles ne sont pas bien espacés entre elles et pas centré
2 - Je pense que pour toute les pages en responsive, il faudra supprimer le background car ça fait vraiment bizarre sur petit écran. On voit une grosse image  et on est un peu perdu, on ne sait pas quoi faire.

**Comment by guaard** [comment]
CONFIRMATION :
1 - Texte trop gros et pas bonne couleur
![screen shot 2015-06-20 at 11 46 55 am](https://cloud.githubusercontent.com/assets/12978755/8267748/3cdd3976-1742-11e5-9311-e85fd633d6e8.png)

**Comment by ajoron** [comment]
OK sauf pour l’écartement des bulles de la première ligne.
