### ISSUE TITLE
QUI SOMMES NOUS

### ISSUE THREAD

**Issue by guaard** [ajoron/fit-and-run#13]
GENERAL :

URL - http://www.fit-and-run.com/a-propos-de-fit-and-run 
CHANGER A - http://www.fit-and-run.com/qui-sommes-nous

ORDINATEUR :
Je pense que pour toutes les pages du footer, il faut supprimé les backgrounds comme je l'ai fait sur les maquettes. Juste laisser le gris texturé en fond.

**Comment by ajoron** [comment]
D'apres préconisation SEO Friendly, URL changée en : http://www.fit-and-run.com/fit-and-run
