### ISSUE TITLE
TARIFS

### ISSUE THREAD

**Issue by guaard** [ajoron/fit-and-run#14]
ORDINATEUR :
Je pense que pour toutes les pages du footer, il faut supprimé les background comme je l'ai fait sur les maquettes. Juste laisser le gris texturé en fond.

1 - Revoir les ombres portées car trop compressées (réf: voir .Psd)
2 - Revoir positionnement et taille du logo MeyClub, car il n'est pas centré dans le bloc (réf: voir .Psd)
![screen shot 2015-06-20 at 12 02 13 pm](https://cloud.githubusercontent.com/assets/12978755/8267811/460d8274-1744-11e5-9b39-8d0c296758f2.png)

**Comment by ajoron** [comment]
Logo repositionné
Ombre porté modifiée
