### ISSUE TITLE
Rajouter bouton facebook et bouton contact dans la barre blanche en haut à droite

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#16]

**Comment by ajoron** [comment]
Bouton Facebook : Pour afficher le bouton, simplement renseigner l'adresse de la page Facebook dans l'admin (Client --> Onglet détails")

Ok pour bouton contactez nous

**Comment by juliensarton** [comment]
Je viens de le rajouter, par contre il apparait super collé au bord de la page à droite

 

--



Julien Sarton

FIT FACTORY

10 rue de Penthièvre

75008 PARIS

+33 7 85 73 10 13

 <http://www.fitfactory.fr> www.fitfactory.fr 

 

De : Axel JORON [mailto:notifications@github.com] 
Envoyé : mardi 23 juin 2015 20:07
À : ajoron/fit-and-run
Cc : juliensarton
Objet : Re: [fit-and-run] Rajouter bouton facebook et bouton contact dans la barre blanche en haut à droite (#16)

 

Bouton Facebook : Pour afficher le bouton, simplement renseigner l'adresse de la page Facebook dans l'admin (Client --> Onglet détails")

Ok pour bouton contactez nous

**Comment by ajoron** [comment]
Fixed
