### ISSUE TITLE
affichage photo sur mobile

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#18]
Sur mobile, la photo de fond de catégorie Training n'est pas centré dr gauche à droite.

Ca n'est pas centré non plus pour le Running, mais la photo tombe bien.

Est ce quelque chose que l'on peut modifier ?

**Comment by juliensarton** [comment]
ERRATUM - Finalement je viens de voir avec Seb, on décide de supprimer les photos header sur la version mobile, pour moins de scrollage

**Comment by ajoron** [comment]
OK, photo de fond supprimée pour mobile

**Comment by juliensarton** [comment]
C’est bien mieux comme ça, Seb avait vu juste

 

--



Julien Sarton

FIT FACTORY

10 rue de Penthièvre

75008 PARIS

+33 7 85 73 10 13

 <http://www.fitfactory.fr> www.fitfactory.fr 

 

De : Axel JORON [mailto:notifications@github.com] 
Envoyé : mercredi 24 juin 2015 01:59
À : ajoron/fit-and-run
Cc : juliensarton
Objet : Re: [fit-and-run] affichage photo sur mobile (#18)

 

OK, photo de fond supprimée pour mobile
