### ISSUE TITLE
email confirmation inscription session - rajouter running/training

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#2]
Dans l'email de confirmation d'inscription à la session, rajouter une icone sous l'adresse pour précisier qu'il s'agit d'une session "Running" ou "Training", avec l'icone qui va avec

**Comment by ajoron** [comment]
Yo, est ce que je peux pas mettre plutot dans le texte  : 

Bonjour <?= $firstname ?>, nous avons le plaisir de vous confirmer votre inscription à la prochaine session [Running ou Fitness] du Fit&Run : 

Parce qu'on a déjà l'image d'entête qui fait référence à l'événement.

Qu'est ce que tu en penses?

**Comment by ajoron** [comment]
Contenu modifé

**Comment by juliensarton** [comment]
Sorry, j’aurais dû te préciser !!

 

J’aurais voulu que l’information training/running s’affiche sous l’adresse du rdv, comme la 4ème info du bloc

 

C’est possible ?

 

 

--



Julien Sarton

FIT FACTORY

10 rue de Penthièvre

75008 PARIS

+33 7 85 73 10 13

 <http://www.fitfactory.fr> www.fitfactory.fr 

 

De : Axel JORON [mailto:notifications@github.com] 
Envoyé : jeudi 25 juin 2015 00:22
À : ajoron/fit-and-run
Cc : juliensarton
Objet : Re: [fit-and-run] email confirmation inscription session - rajouter running/training (#2)

 

Contenu modifé

**Comment by juliensarton** [comment]
Ah merde j’ai répondu à ta question dans un autre mail plus récent !

 

Je préfèrerais qu’on mette l’info training/running dans le bloc que je t’ai décrit, car c’est dans ce bloc que sont toutes les infos liées à l’évènement, c’est la que tu regardes vraiment le résumé de ta prochaine session.

 

La phrase du dessus est une phrase générique, « nous avons le plaisir de vous confirmer……. », je trouve que l’info training/running n’y a pas sa place, et que le sportif risque de passer à côté car il va directement se focaliser sur les bloc du dessous

 

--



Julien Sarton

FIT FACTORY

10 rue de Penthièvre

75008 PARIS

+33 7 85 73 10 13

 <http://www.fitfactory.fr> www.fitfactory.fr 

 

De : Axel JORON [mailto:notifications@github.com] 
Envoyé : mercredi 24 juin 2015 22:54
À : ajoron/fit-and-run
Cc : juliensarton
Objet : Re: [fit-and-run] email confirmation inscription session - rajouter running/training (#2)

 

Yo, est ce que je peux pas mettre plutot dans le texte : 

Bonjour <?= $firstname ?>, nous avons le plaisir de vous confirmer votre inscription à la prochaine session [Running ou Fitness] du Fit&Run : 

Parce qu'on a déjà l'image d'entête qui fait référence à l'événement.

Qu'est ce que tu en penses?

**Comment by ajoron** [comment]
OK Fixed
