### ISSUE TITLE
.fr et .com

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#21]
fit-and-run.fr ne redirige pas fit-and-run.com, ca qui devraît être le cas

Bizarrement, j'ai fait des modifs pour le titre sur la page d'accueil, sous le logo, et je les vois seulement sur le .fr, et pas sur le .com

**Comment by ajoron** [comment]
OK redirection effectuée

**Comment by juliensarton** [comment]
La redirection du .fr vers le .com marche bien.

 

Par contre, je ne vois la phrase d’accroche sous le logo :

 



 

--



Julien Sarton

FIT FACTORY

10 rue de Penthièvre

75008 PARIS

+33 7 85 73 10 13

 <http://www.fitfactory.fr> www.fitfactory.fr 

 

De : Axel JORON [mailto:notifications@github.com] 
Envoyé : mercredi 24 juin 2015 03:15
À : ajoron/fit-and-run
Cc : juliensarton
Objet : Re: [fit-and-run] .fr et .com (#21)

 

OK redirection effectuée

**Comment by ajoron** [comment]
Soucis de cache je crois. Car la jai tappé www.fit-and-run.com et ca na pas
affiché la baseline. J'ai ensuite fait juste fit-and-run.com et là la
baseline est apparu... trop chelou. Après plusieurs refresh (F5) ca a
marché
