### ISSUE TITLE
Dégradé photo de fond + barre blanche

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#22]
Je pense que la photo de fond, à la fois Training et Running, doit être beaucoup plus dégradé pour vraiment finir sur du blanc.

Ce qui permettra de faire en sorte que la barre blanche qui sommesnous/tarifs/etc... soit elle aussi en dégradé comme sur la home page

**Comment by ajoron** [comment]
Ok. Le mieux serai qur tu mz fournisse directement les photos avec les dégradé. Je me concentre sur le reste comme ca

**Comment by juliensarton** [comment]
Je transfère à Seb pour qu il te l envoie !

Merci Seb!

-

Julien Sarton
FIT FACTORY
10 rue de Penthievre
75008 Paris
07 85 73 10 13

---- Axel JORON a écrit ----

**Comment by ajoron** [comment]
En fait il me la faudrai en bonne résolution. Car j'ai essayé de lextraire
depuis le psd mais la resolution était pourri... donc seb si tu peux me
fournir ca en bonne résolution mais en jpeg, pas en png avec transparence
car sinon l'image fait 5mo et cest pas du tout viable pour le temps
d'affichage. Pas plus de 800ko ca serai parfait. Resolution genre 2200px de
largeur ca serai bien aussi (je me rappelle plus la hauteur ratio )

**Comment by ajoron** [comment]
OK Done
