### ISSUE TITLE
Icones contacts/facebook/Insta...

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#23]
Est ce qu'on peut afficher, sur la home page comme sur les autres pages, seulement 3 icônes >> facebook + youtube + instagram (dans cet ordre la)

Google + c'est pas la peine de l'afficher nulle part, on s'en servira pas

Et pour l'icone contact en forme d'enveloppe, je préfère l'enlever car il est trop différent des autres icones facebook/youtube/insta, ca fait pas harmonieux

**Comment by ajoron** [comment]
Je vais voir si je trouve pas un autre icone + harmonieux

**Comment by ajoron** [comment]
Autre remarque :

Mec, pour les logos réseaux sociaux, il s'affiche uniquement si tu as entré
une url dans les champs correspondant dans le paramétrage du client onglet
divers. Si champ rempli icone affiché, si champ vide icone ne s'affiche pas

**Comment by ajoron** [comment]
![image](https://cloud.githubusercontent.com/assets/8795122/8337756/d0fd9d7c-1a61-11e5-9626-44a65026f2ce.png)
 
j'ai trouvé ca. ca te va?

**Comment by juliensarton** [comment]
Yes ça me paraît bien, mais met le à la fin de la liste à droite stp

-

Julien Sarton
FIT FACTORY
10 rue de Penthievre
75008 Paris
07 85 73 10 13

---- Axel JORON a écrit ----

**Comment by ajoron** [comment]
OK done!
