### ISSUE TITLE
GENERAL

### ISSUE THREAD

**Issue by guaard** [ajoron/fit-and-run#26]
- Les ombres des bulles coupées à gauche et à droite.

MENU :

- Pas la mm espace à gauche du logo Fit and Run et les picto "social network" à droite.
- Training et Running pas centrer entre le LOGO et les picto "social network".

**Comment by guaard** [comment]
Rétrécir la MAP GOOGLE en version responsive pour que se soit plus simple à scroller

**Comment by ajoron** [comment]
OK fixed
