### ISSUE TITLE
Page tarifs

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#3]
Modification du premier paragraphe : "Le règlement des sessions est à réaliser sur place.
Sont acceptés les paiement en espèces, chèque ou carte bancaire".

+ Ne pas aller à la ligne après chaque phrase du 2ème paragraphe. Car sur une grande résolution comme mon ordi, ca fait moche

+ le logo Meyclub en bas n'est pas bien centré en hauteur

+ dans le paragraphe Meyclub, ne pas aller à la ligne entre les 2 phrases.

**Comment by ajoron** [comment]
Ok
