### ISSUE TITLE
Problème Date de naissance

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#5]
J'ai créé mon compte via facebook, mais la date par défaut qui est indiqué dans mon profil fit&run est le 20 juin 1997, alors que dans facebook j'ai bien indiqué que j'étais né le 11 juin 1985

**Comment by ajoron** [comment]
Comportement normal. On ne récupère pas la date de naissance du profil Facebook

**Comment by juliensarton** [comment]
J’avais oublié. Du coup si je me rappelle bien c’est la date du jour – 18 ans qui s’affiche, pour être sûr que la personne soit majeure ?

 

--



Julien Sarton

FIT FACTORY

10 rue de Penthièvre

75008 PARIS

+33 7 85 73 10 13

 <http://www.fitfactory.fr> www.fitfactory.fr 

 

De : Axel JORON [mailto:notifications@github.com] 
Envoyé : mercredi 24 juin 2015 03:00
À : ajoron/fit-and-run
Cc : juliensarton
Objet : Re: [fit-and-run] Problème Date de naissance (#5)

 

Comportement normal. On ne récupère pas la date de naissance du profil Facebook

**Comment by ajoron** [comment]
Ouep
