### ISSUE TITLE
Partager sur facebook

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fit-and-run#7]
Il y a encore le texte du GTR ! Normal je t'ai pas donné le texte :)

"Je participe aux sessions Fit&Run !

Toi aussi viens t'entraîner avec nous! Infos et réservations sur www.fit-and-run.com "

Et pour l'image, tu peux me rappeler la dimension qu'elle doit avoir ? je vais rajouter le logo sur une des photos qu'on a

**Comment by ajoron** [comment]
OK à tester

**Comment by ajoron** [comment]
Modif effectuée, à voir selon MAJ du cache de Facebook sur meta tags de la page

**Comment by ajoron** [comment]
OK, Infos mises à jour.

Est ce que tu valides? Pour l'image, est ce que tu veux en mettre une autre?
Si tu veux en mettre une autre, je te laisse le soin d'en faire une au format : 1200x627

Thanks

![image](https://cloud.githubusercontent.com/assets/8795122/8387925/80d615a2-1c11-11e5-981d-98db8ce5ffd1.png)
